=== Upgrade notes

==== Upgrade from Rudder 4.0 or older

Direct upgrades from 4.0.x and older are no longer supported on 4.3.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions, and then upgrade to 4.3.

==== Upgrade from Rudder 4.1 or 4.2

Migration from 4.1 or 4.2 are supported, so you can upgrade directly to 4.3.

==== Compatibility between Rudder agent 4.3 and older server versions

===== 4.1.x and 4.2.x servers

Rudder agents 4.3.x are compatible with 4.1 and 4.2 Rudder servers.

===== Older servers

Rudder agents 4.3.x are not compatible with Rudder servers older than 4.1.
You need to upgrade your server to a compatible version before the agents.

==== Compatibility between Rudder server 4.3 and older agent versions

===== 4.1.x and 4.2.x agents

Rudder agent 4.1.x and 4.2.x are fully compatible with Rudder server 4.3.x. It is
therefore not strictly necessary to update your agents to 4.3.x.

===== Older agents

These agents are not compatible with Rudder 4.3, and you have to upgrade them. 
Be careful to follow the upgrade path explained <<_upgrade_from_rudder_4_0_or_older, above>>.

==== Protocol for reporting

Rudder uses syslog messages over UDP by default for reporting (since 3.1), but if you upgraded
your server from a previous version, you will keep the previous setting which uses
syslog messages over TCP.

You should consider switching to UDP (in *Administration* -> *Settings* -> *Protocol*),
as it will prevent breaking your server in
case of networking or load issues, or if you want to manage a lot of nodes.
The only drawback is that you can lose reports in these situations. It does not
affects the reliability of policy enforcement, but may only temporarily affects
reporting on the server.
Read <<_rsyslog, perfomance notes>> about rsyslog for detailed information.


