=== On Debian or Ubuntu

Following commands are executed as the +root+ user.

Add the Rudder project repository:

----

echo "deb http://www.rudder-project.org/apt-4.3/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/rudder.list

----

Update your local package database to retrieve the list of packages available on our repository:

----

apt-get update

----

For Rudder Server, upgrade all the packages associated to +rudder-server-root+:

* With apt-get:

----

apt-get install rudder-server-root ncf ncf-api-virtualenv

----

and after the upgrade of these packages, restart jetty to apply the changes on the Web application:

----

service rudder-jetty restart

----

For Rudder Agent, upgrade the +rudder-agent+ package:

----

apt-get install rudder-agent

----

[WARNING]

====

Rudder includes a script for upgrading all files, databases, etc... which need
migrating. Therefore, you should not replace your old files by the new ones
when apt-get/aptitude asks about this, unless you want to reset all your parameters.

====

[WARNING]

====

Rudder 4.1 requires Java RE version 8 or more, which is not packaged be default on Debian 7 nor Ubuntu 14.04
On these platforms, prior to upgrade Rudder, you will need to install Java RE 8, either from Oracle site https://www.java.com
or through any other means of your choice

====


You can now xref:12_upgrade/60_technique_upgrade.adoc#_technique_upgrade[upgrade your local techniques].

