= Install Rudder agent on Windows systems

[TIP]

====

Windows agents are only available with a subscription and can be downloaded on https://download.rudder.io/misc/windows/.

====

== Installation for Windows server 2012R2 and later

The agent is currently distributed via an `msi` installer which both support graphical and cli based installations.

An inventory will be run after the installation to send an up-to-date inventory to the policy-server after each installation/upgrade.

The agent comes without digital signature, you may need to allow powershell to execute remote signed source code to be able to properly install the agent.
In some environment, this policy change can lead to security issues, please read the dedicated Microsoft Windows https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2&viewFallbackFrom=powershell-6[documentation].
This can be done in powershell by executing the following command:

----
Set-ExecutionPolicy RemoteSigned
----

=== CLI Installation

Use `msiexec` with the `/quiet` switch to make the installation in silent mode.

----
msiexec /i <absolute path to rudder agent>.msi /quiet POLICYSERVER=my.rudder.server
----

=== Installer options

[cols="1,1"]
|===
|POLICYSERVER (optional)
|Hostname or ip of the policy server to overwrite the `policy-server.conf` file.


|SCHEDULEDTASKUSER (optional)
|Overwrite the user that will be used to run the scheduled task responsible of running the agent every 5minutes.
If left empty, the task will run as the `SYSTEM` account.


|SCHEDULEDTASKPASSWORD (optional)
|Only used with the `SCHEDULEDTASKPASSWORD` option. Password of the user.

|/L*v <path to logfile>
|MSI verbose installation log.

|/quiet
|MSI non graphical installation.
|===

The `SCHEDULEDTASK*` options are only available through the CLI, and when used, the agent will not try to modify the defined task afterward without manual intervention.
The scheduled tasks can be manually modified using the rudder command `rudder agent check-scheduled-tasks`.

== Configuration

The policy server configuration can be provisionned prior to the installation by writing its hostname or IP in the file:

----
C:\Program Files\Rudder\etc\policy-server.conf
----
Proxy options for the agent can be pre-configured if needed, see the https://docs.rudder.io/reference/7.3/plugins/windows.html#_proxy_settings[dedicated documentation].

== Logs

To get install logs, use msiexec's option `/L*V C:\MyLogFile.txt`, other verbose log files are available in `C:\Program Files\Rudder\logs`.
You can also get the rudder agent run logs by running this command: `rudder agent run -v -LogFile C:\debug.txt`

[WARNING]

====

The MSI install log file is a binary data file, some usual text editors may not be able to read it.

====

== Requirements for non server or server version older than 2012R2

Desktop versions are not officially supported but should be mostly compatible as long as the requirements listed below are filled.

[cols="1,1"]
|===
|Powershell
|version 4 or later

|.NET
|version 4.5 or later

|PSDesiredStateConfiguration
|installed
|===

For `Windows Server 2008R2` and `Windows Server 2012` you can upgrade the `PowerShell` version by following for instance, https://social.technet.microsoft.com/wiki/contents/articles/20623.windows-78-and-windows-server-2008-r22012-step-by-step-upgrading-powershell-to-version-4.aspx[this guide].

On desktop or old Windows versions you may need to activate the `DSC` features and `WinRM` features.
Please note that older desktop versions (`Windows 7 and 8`), you will need to install `PowerShell 4` and make sure `WinRM` is activated with the following command:

----
Set-WSManQuickConfig DSC
----


== Versioning policy

The agent version follows the rudder version schema for its first three digits. As MSI requires a four digit based versioning, the fourth is used to describe the release type.
Timestamps are calculated from the 1 January 2020.

[cols="1,1"]
|===
|alpha
|x.y.z.0000000000<timestamp>

|beta
|x.y.z.0<patch version>0000000

|rc
|x.y.z.1<patch version>0000000

|release
|x.y.z.2000000000

|nightly
|x.y.z.109<timestamp>

|alpha-nightly
|x.y.z.000<timestamp>

|beta-nightly
|x.y.z.0<patch version><timestamp>

|rc-nightly
|x.y.z.1<patch version><timestamp>
|===
