site:
  title: Rudder Documentation
  start_page: get-started::home
  url: https://docs.rudder.io
output:
  dir: ./build/sites/site
content:
  sources:
  - url: .
    branches: master
    start_path: src/get-started
  - url: .
    branches: master
    start_path: src/rudder-by-example
  - url: ./doc-build
    branches: ["branches/rudder/8.1", "branches/rudder/8.2", "branches/rudder/8.3", "branches/rudder/9.0"]
    start_path: src/reference
  - url: ./changelogs-build
    branches:
    - "branches/rudder/2.3"
    - "branches/rudder/2.4"
    - "branches/rudder/2.5"
    - "branches/rudder/2.6"
    - "branches/rudder/2.7"
    - "branches/rudder/2.8"
    - "branches/rudder/2.9"
    - "branches/rudder/2.10"
    - "branches/rudder/2.11"
    - "branches/rudder/3.0"
    - "branches/rudder/3.1"
    - "branches/rudder/3.2"
    - "branches/rudder/4.0"
    - "branches/rudder/4.1"
    - "branches/rudder/4.2"
    - "branches/rudder/4.3"
    - "branches/rudder/5.0"
    - "branches/rudder/6.0"
    - "branches/rudder/6.1"
    - "branches/rudder/6.2"
    - "branches/rudder/7.0"
    - "branches/rudder/7.1"
    - "branches/rudder/7.2"
    - "branches/rudder/7.3"
    - "branches/rudder/8.0"
    - "branches/rudder/8.1"
    - "branches/rudder/8.2"
    - "branches/rudder/8.3"
    - "branches/rudder/9.0"
    start_path: src/changelogs
