= Introduction

Rudder is a an *automation* and *compliance* solution dedicated to production constraints.
This guide is designed to help you discover Rudder workflow, and will make you able to:

* Setup Rudder agent
* Manage Nodes with Rudder
* Create configuration polices using built-in components
* Create your own configuration policies
* Apply and control the enforcement of these policies

It requires no prior knowledge about configuration management,
only very basic Unix command-line skills.

[NOTE]

====

This guide is targeted for the lastest major release of Rudder, but
applies to all Rudder versions.

====

== Goal

In this guide, we will guide you through the setup of a test platform including:

* A base security configuration for our nodes, deploying a user and an SSH configuration
* A static website built from a static site generator on a node

== Rudder concepts

Rudder allows managing the configuration of machines

But what is configuration:

* Package httpd installed in version 2.4.12
* Service ntpd is currently running
* SSH connection using passwords are disabled

Configuration is managed through the definition of an expected state.

This state is applied by Rudder, and the information about its application
is continuously updated on the server.
