= Install Rudder root server

== on Amazon Linux 2023

include::{partialsdir}/quick_server.adoc[]

include::{partialsdir}/server_notes.adoc[]

include::{partialsdir}/rpm_key.adoc[]

include::{partialsdir}/al2023_repo.adoc[]

To be able to install plugins on your Rudder server, you will need to https://github.com/amazonlinux/amazon-linux-2023/issues/414[replace the `gnupg2-minimal` package by the `gnupg2` package].
To begin the installation, you should simply install the rudder-server
meta-package, which will install the required components:

----

yum swap gnupg2-minimal gnupg2
yum install rudder-server

----

include::{partialsdir}/initial_config.adoc[]


== on Amazon Linux 2

To install a Rudder Server on Amazon Linux 2, you need a subscription and access to the private repositories.

Then make sure `amazon-linux-extras` is installed:

----

which amazon-linux-extras

----

If it is not installed, install it:

----

sudo yum install -y amazon-linux-extras

----

Finally, you need to install postgresql 11 and openjdk 11 (more recent versions should work too):

----

amazon-linux-extras install postgresql11 java-openjdk11-headless

----

Depending on your exact version of Amazon Linux 2 and corresponding repositories, `java-openjdk11-headless`
may not be available. In that case, you may need to install `java-11-amazon-corretto-headless` (version
of OpenJDK11 built and maintained by Amazon) or `java-openjdk11` (non headless version of OpenJDK with some
frontend related dependencies).

Finally, just follow the standard Rudder installation for xref:installation:server/rhel.adoc[RHEL/CentOS] documentation.

NOTE: As Amazon Linux 2 is based on RHEL 7, the Amazon Linux repository is still named `RHEL_7` even if RHEL/CentOS 7 are not supported as Rudder servers anymore.
