= Install Rudder root server on Amazon Linux 2

Amazon Linux 2 is derived from RHEL 7.

Base RHEL 7 is not supported anymore because of missing components, but Amazon Linux 2
provides amazon-linux-extras that contains missing parts.

To install a Rudder Server on Amazon Linux 2 you first need a support access to
Rudder downloads with RHEL 7 server access.

Then make sure amazon-linux-extras is installed:

----

which amazon-linux-extras

----

If it is not installed, install it:

----

sudo yum install -y amazon-linux-extras

----

Finally, you need postgresql 11 and openjdk 11 (more recent versions should work too):

----

amazon-linux-extras install postgresql11 java-openjdk11-headless

----

Depending on your exact version of Amazon Linux 2 and corresponding repositories, `java-openjdk11-headless`
may not be available. In that case, you may need to install `java-11-amazon-corretto-headless` (version
of OpenJDK11 built and maintained by Amazon) or `java-openjdk11` (non headless version of OpenJDK with some
frontend related dependencies).

Finally, just follow the standard Rudder installation for xref:installation:server/rhel.adoc[RHEL/CentOS] documentation.
