==== Share files between nodes

Rudder 4.1 introduced a way to share files from one node to another.
It allows a node to send a file to its relay, which will make it available
for another target node, that has to to specifically download it.

This file sharing method is secured by:

* The control of uploaded file signature by the server, to check it matches the source node's private key.
* The same mechanism as standard file copy in Rudder to download the shared file from the server.

It also includes a ttl mechanism that allows sharing a file for a limited amount of time.

To use this feature, two generic methods are available in the technique editor:

* xref:90_reference/50_generic_methods.adoc#sharedfile_from_node[sharedfile_from_node]: To download a file shared from another node.
* xref:90_reference/50_generic_methods.adoc#sharedfile_to_node[sharedfile_to_node]: To make a file available to another node.

See the documentation of these methods for details about the required parameters, 
and especially xref:90_reference/50_generic_methods.adoc#sharedfile_to_node[sharedfile_to_node] for a complete usage example.

