= Upgrade notes

[WARNING]

====

Before upgrading a Rudder server, you should make a backup by following the
xref:administration:procedures.adoc#_migration_backups_and_restores[backup procedure].

====

== Plugins disabled during upgrade

Each time Rudder is upgraded, plugins are disabled. You need to enable them 
back after upgrade.

For that, start by checking if update are available for you new version (it will
be mandatory for a minor or major version upgrade) and enable them back.

If you have a subscription, it can done directly with the following commands:

----

rudder package update
rudder package upgrade-all
rudder package plugin enable-all

----

Without a subscription, proceed as you usually do get the latest plugin package, 
and install it from file:

----

rudder package install-file /path/to/plugin.rpkg

----


You can also check for the state of all plugins:

----

rudder package list --all

----

And enable only a chosen one, for example for scale-out relay plugin:

----

rudder package enable rudder-plugin-scale-out-relay

----

More information about `rudder package` command is available with `rudder package --help`.

== Upgrade from Rudder 6.0

include::{partialsdir}/bcrypt.adoc[]

Upgrade from Rudder 6.0 is supported.

[WARNING]
====

Starting from Rudder 7.0, the syslog reporting protocol is removed, and reporting now uses HTTP reporting,
which requires a 6.0+ agent.

If you are upgrading from a previous version, you can switch to HTTPS reporting
if you have not done it yet, to test that everything is ready for it.

====

[WARNING]
===

Rudder agent 7.0 and later use a standardized versioning scheme as described in https://docs.rudder.io/versions

If you parse the output of `rudder agent version` you may expect some little change in its output.

Previous version of this command directly outputed the package version as provided by the system.
It now outputs the same rudder version for every system.

===


[NOTE]
====

The technique tools folder (in `/var/rudder/tools`), that was previously used to synchronize tools used by the system
techniques is not used anymore. All tools have been migrated into the technique that used them.

The folder is left in place, but not automatically shared anymore.

If you relied on the tools copy mechanism to share files, you can replace it by a standard recursive copy
from the shared files.

====

[NOTE]
====

The executable `/opt/rudder/bin/rudder-pkg` can now be used with the command `rudder package`, and can now
list, search and install plugins and their licenses directly from a repository.

====

[NOTE]
====

Rudder 6.1 comes with a new hash function: https://en.wikipedia.org/wiki/Bcrypt[Bcrypt] which allows safer password storage. To switch from a previous hash function (SHA1, SHA256, SH512, MD5) to BCrypt you should change the `hash` parameter in `/opt/rudder/etc/rudder-users.xml` to `bcrypt` and update all password.
To update all passwords you have two ways to proceed: 

* You can do it manually in the same file by using this command in a terminal to generate a new hash:
----
htpasswd -nBC 12 "" | tr -d ':\n' | sed 's/$2y/$2b/'
----
* Directly from the User Management plugin (you should at least update the administrator's password manually to log in the first time) and use the interface to update all password.

====

[WARNING]
====

Upgrading to versions before 6.0.3 leads to several errors (service not started, ldap conf not updated to new format ...), all these bugs are fixed in 6.0.3 and you consider upgrading at least to 6.0.3.

====

[WARNING]
====

Upgrading to 6.0.3 disables all plugins you may have installed because compatibility of previous 6.0 plugins are not compatible with 6.0.3, please reinstall your plugins to their latest versions.

====

== Upgrade from Rudder 5.0 or older

Direct upgrades from 5.0 versions and older are no longer supported on 7.0.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions, and then upgrade to 7.0.

== Compatibility between Rudder agent 7.0 and older server versions

=== 6.0, 6.1 and 6.2 servers

Rudder agents 7.0 are compatible with 6.0, 6.1 and 6.2 Rudder servers.

=== Older servers

Rudder agents 7.0 are not compatible with Rudder servers older than 6.0.
You need to upgrade your server to a compatible version before the agents.

== Compatibility between Rudder server 7.0 and older agent versions

=== 6.0, 6.1 and 6.2 agents

Rudder agent 6.0, 6.1 and 6.2 are fully compatible with Rudder server 7.

=== Older agents

These agents are not compatible with Rudder 7.0, and you have to upgrade them.
Be careful to follow the upgrade path explained xref:upgrade.adoc#_upgrade_from_rudder_5_0_or_older[above].
