= Upgrade notes

[NOTE]

====

Before upgrading a Rudder server, you should make a backup by following the
xref:administration:procedures.adoc#_migration_backups_and_restores[backup procedure].

====

== Plugins upgrade

If your server is connected to the Internet (directly or through a proxy), and you have configured
your account in the setup wizard (or directly in `/opt/rudder/etc/rudder-pkg/rudder-pkg.conf`), the upgrade process will take care of upgrading to
plugins to a compatible version.

If it is not the case, you will need to download the new ones from https://downloads.rudder.io[downloads.rudder.io].
and install them following the usual xref:reference:plugins:index.adoc[installation procedure].

You can check the current state of plugins with:

----

rudder package list --all

----

== Upgrade from Rudder 7.3 to 8.0

Upgrade from Rudder 7.3 is supported.

=== API tokens

The API tokens storage changes starting from 8.0.
Plain tokens are now only available once after creation or
re-generation, and the server only stores a hash.
This improves the security and traceability of the tokens.

It does not change anything from a user perspective: the
tokens are still a 32-character string, and are used in the same way
in the requests, all changes are in the server.

For compatibility, previous tokens will continue working
after upgrade, and a warning will be displayed in the interface
if you still use them.
Users are encouraged to plan replacement of the old tokens
after upgrade, as they will stop
working in a future Rudder version.

=== Node delete mode is "erase"

Historically, Rudder has supported a node delete mode where node information
was moved in a dedicated LDAP branch and not deleted in addition to the 
real deletion of information. The choice was configured by property
`rudder.nodes.delete.defaultMode` and the default was `erase` since Rudder 7.2.
At the same time, the `move` mode was deprecated.
As of Rudder 8.0, the old `move` mode is removed and node information is erased
from the database when a node is deleted.

== Upgrade from Rudder 7.2 or older to 7.3

Direct upgrades from 7.2 versions and older are no longer supported on 8.0.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions, and then upgrade to 8.0.

