= Upgrade notes

[NOTE]

====

Before upgrading a Rudder server, you should make a backup by following the
xref:administration:procedures.adoc#_migration_backups_and_restores[backup procedure].

====

== Plugins upgrade

If your server is connected to the Internet (directly or through a proxy), and you have configured
your account in the setup wizard (or directly in `/opt/rudder/etc/rudder-pkg/rudder-pkg.conf`), the upgrade process will take care of upgrading to
plugins to a compatible version.

If it is not the case, you will need to download the new ones from https://downloads.rudder.io[downloads.rudder.io].
and install them following the usual xref:reference:plugins:index.adoc[installation procedure].

You can check the current state of plugins with:

----

rudder package list --all

----

== Upgrade from Rudder 7.3 to 8.0

Upgrade from Rudder 7.2 is supported. There are no specific upgrade notes.

include::{partialsdir}/msi.adoc[]

== Upgrade from Rudder 7.2 or older to 7.3

Direct upgrades from 7.2 versions and older are no longer supported on 8.0.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions, and then upgrade to 8.0.

