= Upgrade notes

[WARNING]

====

Before upgrading a Rudder server, you should make a backup by following the
xref:administration:procedures.adoc#_migration_backups_and_restores[backup procedure].

====

== Plugins disabled during upgrade

Each time Rudder is upgraded, plugins are disabled. You need to enable them
back after upgrade.

For that, start by checking if update are available for you new version (it will
be mandatory for a minor or major version upgrade) and enable them back.

If you have a subscription, it can done directly with the following commands:

----

rudder package update
rudder package upgrade-all
rudder package plugin enable-all

----

Without a subscription, proceed as you usually do get the latest plugin package,
and install it from file:

----

rudder package install-file /path/to/plugin.rpkg

----


You can also check for the state of all plugins:

----

rudder package list --all

----

And enable only a chosen one, for example for scale-out relay plugin:

----

rudder package enable rudder-plugin-scale-out-relay

----

More information about `rudder package` command is available with `rudder package --help`.

== Upgrade from Rudder 6.1 or 6.2

include::{partialsdir}/bcrypt.adoc[]

Upgrade from Rudder 6.1 or 6.2 is supported.

[WARNING]
====

Syslog is not supported anymore as reporting protocol as of 7.0.

====

[WARNING]
===

Rudder agent 7.0 and later use a standardized versioning scheme as described in https://docs.rudder.io/versions

If you parse the output of `rudder agent version` you may expect some little change in its output.

Previous version of this command directly outputted the package version as provided by the system.
It now outputs the same rudder version for every system.

===

== Upgrade from Rudder 6.0 or older

Direct upgrades from 6.0 versions and older are no longer supported on 7.0.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions, and then upgrade to 7.0.

== Compatibility between Rudder agent 7.0 and older server versions

=== 6.1 and 6.2 servers

Rudder agents 7.0 are compatible with 6.1 and 6.2 Rudder servers.

=== Older servers

Rudder agents 7.0 are not compatible with Rudder servers older than 6.1.
You need to upgrade your server to a compatible version before the agents.

== Compatibility between Rudder server 7.0 and older agent versions

=== 6.1 and 6.2 agents

Rudder agent 6.1 and 6.2 are fully compatible with Rudder server 7.0.

=== Older agents

These agents are not compatible with Rudder 7.0, and you have to upgrade them.
Be careful to follow the upgrade path explained xref:upgrade.adoc#_upgrade_from_rudder_5_0_or_older[above].
