==== Agent execution frequency on nodes

===== Checking configuration (CFEngine)

By default, Rudder is configured to check and repair configurations using the CFEngine
agent every 5 minutes, at 5 minutes past the hour, 10 minutes past the hour,
etc.

The exact run time on each machine will be delayed by a random interval, in
order to "smooth" the load across your infrastructure (also known as "splay
time"). This reduces simultaneous connections on relay and root servers (both
for the CFEngine server and for sending reports).

See xref:41_advanced_node_management/10_node_management.adoc#_change_the_agent_run_schedule[Change the agent run schedule] Section to see how to configure it 


===== Inventory (FusionInventory)

The FusionInventory agent collects data about the node it's running on such as
machine type, OS details, hardware, software, networks, running virtual
machines, running processes, environment variables...

This inventory is scheduled once every 24 hours, and will happen in between
0:00 and 5:00 AM. The exact time is randomized across nodes to "smooth" the
load across your infrastructure.

