=== New directives default naming scheme

When a new directive is created, by default the 'Name' field is filled
with the Technique name. For example, if you create a new Directive from 
the 'Users' Technique, the Name field will get the value: "Users".

This not always what you want, especially for your custom Techniques. So you
have the possibility to define new default values for Name, at Technique or
at Technique and Version granularity. 

This is done by adding or updating the file: 
`/var/rudder/configuration-repository/techniques/default-directive-names.conf`.

That file need to be commited in git, and the Technique library reloaded 
to take effect:

----
cd /var/rudder/configuration-repository/techniques/
vi default-directive-names.conf
 ....
git add default-directive-names.conf
git commit -m "Change default names for new directives"
rudder server reload-techniques
----

The file format is a simple `techniqueId[/optionalVersion]: default name to use` format. 
The Technique ID is the name of the directory containing the Technique version directory
in `/var/rudder/configuration-repository/techniques`.

For example, if we imagine that in your company, you have the internal
convention to create one directive by user role with the login in the
name, you would prefer to have a default value to:

----
Role <user-role>: <matching-login>
----

And then, for Users Technique version 7, you changed your mind and now 
use the scheme:

----
Role: [user-role] (with login [login])
----

Then the file will look like:

----
# Default pattern for new directive from "userManagement" technique:
userManagement= Role <user-role>: <matching-login>

# For userManagement version 2.0, prefer that pattern in new Directives:
userManagement/7.0: Role: [user-role] (with login [login])
----


