[[plugins-management]]
= Manage plugins

Rudder is an extensible software. The *Plugins*
menu sums-up information about loaded plugins, their version and their
configuration.

A plugin is an `.rpkg` file (for "Rudder package").

== Get plugins

There are two types of Rudder pre-packaged plugins:

* Integration plugins, that allow linking Rudder to other tools (monitoring, inventory, notification, etc.). They are freely available.
* Advanced features plugins (reporting, validation workflow, etc.) which are part of the Rudder subscription.

To download free plugins or get information about plugins included in the subscription,
read the https://rudder.io/plugins/[dedicated page on rudder.io].

== Install a plugin

To install a plugin, you can use the `rudder package` command.
You can configure it in `/opt/rudder/etc/rudder-pkg/rudder-pkg.conf`

It can retrieve plugins and their licenses from the Rudder repository.

----
# Update the repository index
rudder package update

# Download and install the latest release of a plugin
rudder package install-file <package_name>

# Download and install the latest nightly of a plugin
rudder package install-file <package_name> --nightly

# Install a local .rpkg file
rudder package install-file <package.rpkg>

# Download all your license from the plugin repository
rudder package licenses
----

You can get information about available plugins with:

----
# List currently installed plugins
rudder package list
# List currently available plugins
rudder package list --all
# List all available versions of a plugin
rudder package search <package_name>
# Display details of a plugin
rudder package show <package_name>
----

You can also enable or disable, or remove a plugin with:

----
rudder package plugin enable <plugin>
rudder package plugin disable <plugin>
rudder package remove <package>
----

See all available commands with:

----
rudder package --help
----

== Install your licenses

Some plugins needs a license to work properly. All your licenses are signed with a key (license.key file)
and there is one file per licensed plugin (<plugin-name>.license). You may have downloaded them from https://download.rudder.io/plugins/licenses

You need to put all files in `/opt/rudder/etc/plugins/licenses` folder, if that directory does not exist please create it.

If the plugin is installed, no need to restart Rudder, it will read the new license and check its compatibility immediatly

include::{partialsdir}/dyn/version-compat.adoc[leveloffset=+1]
