[[plugins-management]]
= Manage plugins

Rudder is an extensible software. The *Plugins*
menu sums-up information about loaded plugins, their version and their
configuration.

A plugin is an `.rpkg` file (for "Rudder package").

== Get plugins

There are two types of Rudder pre-packaged plugins:

* Integration plugins, that allow linking Rudder to other tools (monitoring, inventory, notification, etc.). They are freely available.
* Advanced features plugins (reporting, validation workflow, etc.) which are part of the Rudder subscription.

To download free plugins or get information about plugins included in the subscription,
read the https://rudder.io/plugins/[dedicated page on rudder.io].

== Install a plugin

To install a plugin, copy the `.rpkg` file on your server, and run:

----
/opt/rudder/bin/rudder-pkg install-file <package.rpkg>
----

You can list currently installed plugins using:

----
/opt/rudder/bin/rudder-pkg list
----

You can also enable or disable, or remove a plugin with:

----
/opt/rudder/bin/rudder-pkg plugin enable <plugin>
/opt/rudder/bin/rudder-pkg plugin disable <plugin>
/opt/rudder/bin/rudder-pkg remove <package>
----

See all available commands with:

----
/opt/rudder/bin/rudder-pkg --help
----

include::{partialsdir}/dyn/version-compat.adoc[leveloffset=+1]
