[[_configure_and_validate]]
== Configuration

=== Configure the agent

Configure the IP address or hostname of the Rudder Root Server in the following file

----

rudder agent policy-server <rudder server ip or hostname>

----

[TIP]

=====

We advise you to use the +IP address+ of the Rudder root server. The DNS name of
this server can also be used if you have a trusted DNS infrastructure
with proper reverse resolutions.

=====

=== Add the node to the server

Several minutes after the start of the agent, the new node should be pending in
the Rudder web interface. You will be able to browse its inventory, and accept it to manage its
configuration with Rudder.

You may force the agent to run and send an inventory by issuing the following command:

----

rudder agent inventory

----

You may force the agent run by issuing the following command:

----

rudder agent run -l

----

The `-l` here prevents the agent from trying to update its policies, which is not possible yet, and only run
with local policies.

[NOTE]

=====

By default, a node listens on port 5309 to allow remote agent trigger. 
This feature is optional and 
xref:reference:modules:usage:pages:advanced_node_management.adoc#disable_listen_port_5309[can be disabled for security reason].

=====



