[[_technique_upgrade]]
=== Technique upgrade

At the first installation, Rudder will automatically deploy a technique library in the
`/var/rudder/configuration-repository/techniques` directory.

When upgrading Rudder to another version, a new (updated) technique library will be deployed
in `/opt/rudder/share/techniques`, and Rudder will automatically take care of updating the system
Techniques in the configuration-repository directory.

However, the other techniques will not be updated automatically (yet), so you will have to do
it yourself.

[CAUTION]

====

Please keep in mind that if you did manual modifications on the techniques in existing directories,
or created new versions of them, you will have some merging work to do.

====

To upgrade you local techniques, run the following commands on the Rudder root server:

----

cd /var/rudder/configuration-repository
cp -a /opt/rudder/share/techniques/* techniques/
git status
# Now, inspect the differences. If no conflict is noticeable, then go ahead.
git add techniques/
git commit -m "Technique upgrade" # Here, put a meaningful message about why you are updating.
rudder server reload-techniques

----

This last command will reload the technique library and trigger a full redeployment on nodes.

Please check that the deployment is successful in the Rudder web interface.
