= Rudder components

== Rudder server

This is the central server that will define configuration for the nodes it manages.
You generally need to install only one Rudder server, except if you have completely
separated environments where each environment requires its own server.

Installation instructions:

* Install a Rudder server on: xref:installation:server/debian.adoc[Debian/Ubuntu] | xref:installation:server/rhel.adoc[RHEL/CentOS] | xref:installation:server/sles.adoc[SLES] | xref:installation:server/al2.adoc[Amazon Linux 2]

* Upgrade a Rudder server on: xref:upgrade:server/debian.adoc[Debian/Ubuntu] | xref:upgrade:server/rhel.adoc[RHEL/CentOS] | xref:upgrade:server/sles.adoc[SLES]

include::{partialsdir}/upgrade_notes.adoc[]

== Node

The machines managed by Rudder are called nodes, and can be any type of machine
(physical, virtual, cloud instance, container, etc).
For a machine to become a managed Node, you need to install the Rudder agent on it.
The agent will run a local inventory and register itself to the Rudder server. Then,
you can accept the node in the Rudder server interface for it to become a managed node.

Installation instructions:

* Install an agent on: xref:installation:agent/debian.adoc[Debian/Ubuntu] | xref:installation:agent/rhel.adoc[RHEL/CentOS/Amazon Linux] | xref:installation:agent/sles.adoc[SLES]

* Upgrade an agent on: xref:upgrade:agent/debian.adoc[Debian/Ubuntu] | xref:upgrade:agent/rhel.adoc[RHEL/CentOS/Amazon Linux] | xref:upgrade:agent/sles.adoc[SLES]


[[relay-servers]]
== Relay (optional)

Relay servers can be added to Rudder, for example to manage a DMZ or to isolate specific
nodes from the main environment for security reasons.

Relay server's purpose is to solve a simple problem: sometimes, one would want to manage
multiple networks from Rudder, without having to allow all the subnet access to the other
for security reasons. A solution for this would be to have a kind of "Rudder" proxy that
would be relaying information between the subnet and the main Rudder server. This is the
reason Rudder relays were created.

Using a relay, you are able to:

* Separate your Rudder architecture into separate entities that still report to one server
* Prevent laxist security exceptions to the Rudder server
* Ease maintenance

Installation instructions:

* Install Rudder relay on: xref:installation:relay/debian.adoc[Debian/Ubuntu] | xref:installation:relay/rhel.adoc[RHEL/CentOS] | xref:installation:relay/sles.adoc[SLES]
* Upgrade Rudder relay on: xref:upgrade:relay/debian.adoc[Debian/Ubuntu] | xref:upgrade:relay/rhel.adoc[RHEL/CentOS] | xref:upgrade:relay/sles.adoc[SLES]
