= Supported Operating Systems

[[node-supported-os, the list of supported Operating Systems for Nodes]]
== Fully supported Operating Systems

Fully supported Operating Systems are systems that we frequently build packages for and test on our servers.

=== For Rudder Nodes

The following operating systems are supported for Rudder Nodes and packages are
available for these platforms:

GNU/Linux:

* Debian 8 and 9

* Red Hat Enterprise Linux (RHEL) / RHEL-like (CentOS, etc) 6 and 7 (64-bit)

* SUSE Linux Enterprise Server (SLES) 11 and 12 (64bit)

* Ubuntu 14.04 LTS (Trusty), 16.04 LTS (Xenial), 18.04 LTS (Bionic) (64-bit)

* Slackware 14 (64-bit)

Other Unix systems:

* IBM AIX 5.3, 6.1 and 7.1

Windows:

* xref:TODO[Microsoft Windows] Server 2008 R2, 2012, 2012 R2, 2016

[TIP]

[[install-on-windows, Install on Microsoft Windows]]

.Windows, Slackware and AIX Nodes

====

* For Microsoft Windows, Rudder agent relies on DSC (Desired State Configuration) included in Powershell 4.0 or later. Packages are available from Normation under subscription only.
* For IBM AIX, packages are available from Normation under subscription only.

Hence, as a starting point, we suggest that you evaluate Rudder on Linux machines. Once
you are accustomed to Rudder, contact Normation to obtain a demo version for
these platforms.

====


[[server-supported-os, the list of supported Operating Systems for Root server]]
=== For Rudder root server or relay server

The following operating systems are supported as a root or relay server:

* Debian 8 and 9

* Red Hat Enterprise Linux (RHEL) / CentOS 7

* SUSE Linux Enterprise Server (SLES) 12 SP1+

* Ubuntu 16.04 LTS (Xenial), 18.04 LTS (Bionic)

== Partially supported Operating Systems

Partially supported Operating Systems are systems that we have built packages for and tested at least once (in some cases, many more times) but that are not currently receiving continuous attention or bug fixes.

[WARNING]

.Partially supported Operating Systems

====

It is possible to use Rudder on other platforms than the fully supported ones.
However, some Techniques may not work properly. If you
wish to get Rudder support on those systems, please get in touch with us!

====

=== For Rudder Nodes

The following operating systems have had an agent built using xref:reference:build.adoc#_building_the_rudder_agent[Building the Rudder Agent]:

* Debian 5 to 7

* Red Hat Enterprise Linux (RHEL) / RHEL-like 3 to 5

* SUSE Linux Enterprise Server (SLES) 10 SP3

* Ubuntu 10.04 LTS (Lucid), 12.04 LTS (Precise)

* FreeBSD

* Solaris 10 and 11

* Raspbian, based on jessie (via dpkg)

* Debian 8 on ARM (armhf version) (via dpkg)

* OpenSUSE (via rpm)

[TIP]

.Building an agent from source

====

You can also follow the xref:reference:build.adoc#_building_the_rudder_agent[build instructions] to build and install Rudder Agent locally on your favorite operating system.
Even if this OS has not been tested by us, there is a reasonable chance that the agent will work successfully.

====

=== For Rudder Root Server

We advise against using a partially supported OS for Rudder server because the server contains
much more code than the agent. This code is tailored against specific OS versions
to work around various system limitations and specificities.
