= Supported operating systems

[[node-supported-os, the list of supported operating systems for nodes]]
== Fully supported operating systems

Fully supported operating systems are systems that we frequently build packages for and test on our servers.

=== For Rudder nodes

==== Rudder Core

[NOTE]
===========

The OS supported in Rudder Core are available in the public repository https://repository.rudder.io/, consult the install section for more details.

===========

The following operating systems are supported for Rudder nodes, and packages are
available freely for these platforms:

[options="header"]
|===

| OS | Version | Architecture

| Debian | 12 and 13 | 64bit
| Ubuntu | 24.04 LTS | 64bit
| Red Hat Enterprise Linux (RHEL) / AlmaLinux, Rocky Linux, Oracle Linux / CentOS Stream | 9 and 10 | 64bit
| SUSE Linux Enterprise Server (SLES) | 15 SP6+ | 64bit
| Amazon Linux | 2023 | 64bit

|===

==== Subscription support

[NOTE]
===========

The subscription supported OS are available in the repository https://download.rudder.io/ it contains the community supported OS and
all the OS only available through a subscription. Consult install sections for more details.

===========

The following operating systems are supported for Rudder nodes and packages are
available for these platforms as part of the https://www.rudder.io/en/pricing/subscription/[Rudder subscription]:

[options="header"]
|===

| OS | Version | Architecture
.2+| Debian | 10 to 13 | 64bit, arm64, armhf (Raspbian)
| 10 to 12 | 32bit
.2+| Ubuntu | 18.04 LTS to 24.04 LTS | 64bit
| 18.04 LTS | 32bit
.2+| Red Hat Enterprise Linux (RHEL) / RHEL-like (CentOS, etc) | 7 to 10 | 64bit
| 9 and 10 | arm64
.1+| SUSE Linux Enterprise Server (SLES) | 12SP5+ and 15SP2+ | 64bit
| Amazon Linux | 2023 | 64bit
| Slackware | 15 | 64bit
| Microsoft Windows Server | 2016, 2019, 2022, 2025 | 64bit
| Microsoft Windows | 10 and 11 | 64bit

|===

[WARNING]

.Supporting Debian-based systems without systemd

====

It is possible to use Rudder on platforms without systemd, but systemd is required
by the package when the distribution supports it.
Please contact the Rudder team if you want a package without systemd on a distribution
where systemd has been removed.

====

[[server-supported-os, the list of supported Operating Systems for Root server]]
=== For Rudder server or relay

[NOTE]

.OS support policy

====

Our general policy for Rudder server is to support the two latest
supported versions. It means:

* Debian _stable_ and _oldstable_
* The two latest Ubuntu LTS versions
* The latest major RHEL/CentOS and SLES versions (plus the previous one if the latest is less than 2 years old)

====

The following operating systems are supported as a Rudder relay or server:

[options="header"]
|===

| OS | Version | Architecture

| Debian | 12 and 13 | 64bit
| Ubuntu | 24.04 LTS | 64bit
| Red Hat Enterprise Linux (RHEL) / AlmaLinux, Rocky Linux, Oracle Linux / CentOS Stream | 9 and 10 | 64bit
| SUSE Linux Enterprise Server (SLES) | 15 SP6+ | 64bit
| Amazon Linux | 2023 | 64bit

|===

== Partially supported Operating Systems

Partially supported Operating Systems are systems that we have built packages for and tested at least once (in some cases, many more times) but that are not currently receiving continuous attention or bug fixes.

[WARNING]

.Partially supported Operating Systems

====

It is possible to use Rudder on other platforms than the fully supported ones.
However, some Techniques may not work properly. If you
wish to get Rudder support on those systems, please get in touch with us!

====

=== For Rudder Nodes

The following operating systems work with packages built for another operating system:

* OpenSUSE LEAP (with SLES packages)
* Amazon Linux and Amazon Linux 2 (with RHEL packages)

[TIP]

.Building an agent from source

====

You can also follow the xref:reference:build.adoc#_building_the_rudder_agent[build instructions] to build and install Rudder Agent locally on your favorite operating system.
Even if we have not tested this OS, there is a reasonable chance that the agent will work successfully.

====

=== For Rudder Root Server

We advise against using a partially supported OS for Rudder server because the server contains
much more code than the agent. This code is tailored against specific OS versions
to work around various system limitations and specificities.
