= Supported Operating Systems

[[node-supported-os, the list of supported Operating Systems for Nodes]]
== Fully supported Operating Systems

Fully supported Operating Systems are systems that we frequently build packages for and test on our servers.

=== For Rudder Nodes

==== Community support

The following operating systems are supported for Rudder Nodes and packages are
available freely for these platforms:

[options="header"]
|===

| OS | Version | Architecture

| Debian | 8, 9, 10 and 11 | 32bit, 64bit
.2+| Ubuntu | 16.04 LTS | 32bit, 64bit
| 18.04 LTS and 20.04 LTS | 64bit
.2+| Red Hat Enterprise Linux (RHEL) / RHEL-like (CentOS, etc) | 6 | 32bit, 64bit
| 7 and 8 | 64bit
| SUSE Linux Enterprise Server (SLES) | 12 and 15 | 64bit

|===

==== Subscription support

The following operating systems are supported for Rudder Nodes and packages are
available for these platforms as part of the https://www.rudder.io/en/pricing/subscription/[Rudder subscription]:

[options="header"]
|===

| OS | Version | Architecture

.3+| Debian | 6 and 7 |32bit, 64bit
| 8 | 32bit, 64bit, armhf (Raspbian)
| 9, 10 and 11 | 32bit, 64bit, arm64, armhf (Raspbian)
.2+| Ubuntu | 10.04 to 16.04 LTS | 32bit, 64bit
| 18.04 and 20.04 LTS | 64bit
| Red Hat Enterprise Linux (RHEL) / RHEL-like (CentOS, etc) | 3, 5 to 8 | 32bit, 64bit
.2+| SUSE Linux Enterprise Server (SLES) | 10SP3 and 11 | 32bit, 64bit
| 12 and 15 | 64bit
| Slackware | 14 | 64bit
| Solaris | 11.4 | 64bit
| IBM AIX | 5.3, 6.1 and 7.1 | ppc
| Microsoft Windows Server | 2008 R2, 2012, 2012 R2, 2016 | 32bit, 64bit

|===

[WARNING]

.Supporting Debian-based systems without systemd

====

It is possible to use Rudder on platforms without systemd, but systemd is required
by the package when the distribution supports it.
Please contact Rudder team if you want a package without systemd on a distribution
where systemd has been removed.

====

[[server-supported-os, the list of supported Operating Systems for Root server]]
=== For Rudder root server or relay server

[NOTE]

.OS support policy

====

Our general policy for Rudder server is to support the two latest
supported versions. It means:

* Debian _stable_ and _oldstable_
* The two latest Ubuntu LTS versions
* The latest major RHEL/CentOS and SLES versions (plus the previous one if the latest is less the 2 years old)

====

The following operating systems are supported as a root or relay server:

[options="header"]
|===

| OS | Version | Architecture

| Debian | 9 and 10 | 64bit
| Ubuntu | 18.04 and 20.04 LTS | 64bit
| Red Hat Enterprise Linux (RHEL) / CentOS | 7 and 8 | 64bit
| SUSE Linux Enterprise Server (SLES) | 12 and 15 | 64bit

|===

== Partially supported Operating Systems

Partially supported Operating Systems are systems that we have built packages for and tested at least once (in some cases, many more times) but that are not currently receiving continuous attention or bug fixes.

[WARNING]

.Partially supported Operating Systems

====

It is possible to use Rudder on other platforms than the fully supported ones.
However, some Techniques may not work properly. If you
wish to get Rudder support on those systems, please get in touch with us!

====

=== For Rudder Nodes

The following operating systems have had an agent built using xref:reference:build.adoc#_building_the_rudder_agent[Building the Rudder Agent]:

* FreeBSD
* Solaris 10

The following operating systems work with packages built for another operating system:

* OpenSUSE LEAP (with SLES packages)
* Amazon Linux and Amazon Linux 2 (with RHEL packages)
* Oracle Linux (with RHEL packages)

[TIP]

.Building an agent from source

====

You can also follow the xref:reference:build.adoc#_building_the_rudder_agent[build instructions] to build and install Rudder Agent locally on your favorite operating system.
Even if this OS has not been tested by us, there is a reasonable chance that the agent will work successfully.

====

=== For Rudder Root Server

We advise against using a partially supported OS for Rudder server because the server contains
much more code than the agent. This code is tailored against specific OS versions
to work around various system limitations and specificities.
