= Upgrade notes

[WARNING]

====

Before upgrading a Rudder server, you should make a backup by following the
xref:administration:procedures.adoc#_migration_backups_and_restores[backup procedure].

====

== Upgrade from Rudder 5.0

Migration from any 5.0 minor version is supported (see below for migration from older versions).

[NOTE]
====

The Rudder packages ncf, ncf-api-virtualenv, rudder-inventory-endpoint, rudder-inventory-ldap, rudder-jetty 
and rudder-techniques have been merged into rudder-webapp. This means that on a server upgrade from Rudder 5.0
those packages will all be removed.

This is normal!

====

[NOTE]
====

The technique tools folder (in `/var/rudder/tools`), that was previously used to synchronize tools used by the system
techniques is not used anymore. All tools have been migrated into the technique that used them.

The folder is left in place, but not automatically shared anymore.

If you relied on the tools copy mechanism to share files, you can replace it by a standard recursive copy
from the shared files.

====

[NOTE]
====

Rudder generic method `condition from command` will change its behaviour in `audit` policy mode starting 6.0.

Before the 6.0 Rudder version, when in audit policy mode, the method was not executing the command passed in
parameters and would always report an error.

In order to limit the compliance drift when switching policy mode we chose to make the method behave in the
exact same way in audit mode than in enforce mode because:

* Audit and enforce policy mode should do the same check on the node, and differ on the remediation part
* The method is mainly used to bypass missing components in the current generic methods library
and so, not applying it in audit restrain Rudder from complex use cases
* The command passed as parameter should always be system impact free, and so, it can be executed without
impacting the overall configuration state of the node

====

[NOTE]
====

Rudder 5.0.9 changes the default log level for the configuration server in Rudder.

This allows easier debugging and tracability of policy updates, so we enabled
it by default, but will produce more logs.
If you want to revert to the previous behavior (which only logs errors):

* On systemd systems

** Create a `/etc/systemd/system/rudder-cf-serverd.service.d/override.conf` file containing:

----
[Service]
Environment=VERBOSITY_OPTION=
----

** Run `systemctl daemon-reload` then `systemctl restart rudder-cf-serverd`

* On systems using the init script

** Edit the `/etc/default/rudder-agent` file:

----
# You need to uncomment and let empty
CFENGINE_COMMUNITY_PARAMS_1=""
----

** Restart the service with `service rudder-agent restart`

Verbosity options can be:

* empty for only errors
* `--inform` for basic messages
* `--verbose` for very detailed logs
* `--debug` for unreasonnably detailed logs

====

[NOTE]
====

The executable `/opt/rudder/bin/rudder-pkg` can now be used with the command `rudder package`, and can now
list, search and install plugins and their licenses directly from a repository.

====

Direct upgrades from 4.3.x and older are no longer supported on 6.0.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions, and then upgrade to 6.0.

== Compatibility between Rudder agent 6.0 and older server versions

=== 5.0 servers

Rudder agents 6.0 are compatible with 5.0 Rudder servers.

=== Older servers

Rudder agents 6.0 are not compatible with Rudder servers older than 5.0.
You need to upgrade your server to a compatible version before the agents.

== Compatibility between Rudder server 6.0 and older agent versions

=== 4.3 and 5.0 agents

Rudder agent 4.3 and 5.0 are fully compatible with Rudder server 6.0. It is
therefore not strictly necessary to update all your agents to 6.0.

=== Older agents

These agents are not compatible with Rudder 6.0, and you have to upgrade them.
Be careful to follow the upgrade path explained xref:upgrade.adoc#_upgrade_from_rudder_4_3_or_older[above].
