= Rudder versions

== Rudder versioning

Rudder releases follow a `X.Y.Z` version scheme (for example, 7.1.2):

* *`X` version increments* are *major* releases. These versions include new features and architecture changes, and the amount of modifications can be considerable. An upgrade path from one major version to the next will always be provided (i.e., upgrading from 5 to 6 is supported, and from 6 to 7 is too, but upgrading directly from 5 to 7 will generally not be – check the xref:reference:installation:upgrade.adoc[upgrade section] of the user manual for specifics). They are released approximately every 9 to 12 months.
* *`Y` version increments* are *minor* releases. These versions include small new features and various improvements, but no major change in the architecture of Rudder. An upgrade path from one minor version to the next ones (for a given major version) will be provided – check the xref:reference:installation:upgrade.adoc[upgrade section] of the user manual for specifics). They are released every few months.
* *`Z` version increments* are *patch* releases. They contains bug or security fixes, and we make a lot of effort to reduce the amount of changes that go into these version (a full change log is always available). Upgrading your Rudder version to the latest patch release is always recommended, and is designed to be easy. They are released every few weeks.

=== Pre-release versioning scheme

Final release just have the version described above: `X.Y.Z`. However before a release we have many steps.

* alpha: only available as nightly so no versioning, expect breakage
* beta: `X.Y.Z~betaN` where N increments for each new beta, this is a version that builds but new feature and breakage should still be expected.
* rc: `X.Y.Z~rcN` where N increments for each new rc, this is a version that should pass most tests and new feature should not happen anymore.
* release: `X.Y.Z̀` which is the final version as described above

=== Nightly versioning scheme

Rudder packages are built every night. There is a nightly scheme for each release step. Note that nightly dependencies between rudder packages are less strict than release dependencies to allow installing even if some packages failed to build.

* alpha: `X.Y.Z~alpha~gitYYYYMMDDHHMM`
* beta: `X.Y.Z~betaN~gitYYYYMMDDHHMM`
* rc: `X.Y.Z~rcN~gitYYYYMMDDHHMM`
* release: `X.Y.Z~gitYYYYMMDDHHMM`

== Rudder life cycle

A maintained version is a major version for which we release minor bug fix releases and communicate about security vulnerabilities.

* Our general policy is to *provide patch releases for an X.Y version during at least 3 months after the next minor or major version* is released to give some time for upgrading.
* For a slower major upgrade pace, Rudder subscription provides (among other benefits) *long-term maintenance of 18 to 24 months after release* (depending on the subscription level) for Rudder major versions, with a minimal upgrade window of 6 to 9 months. You can read more about it on the https://www.rudder.io/en/pricing/subscription/[subscription page].

You can subscribe to the https://www.rudder.io/en/expand/new-releases-security/[rudder-announce mailing-list] to receive release and end of life announcements. Here is a table of all versions of Rudder, their status, release dates and planned maintenance termination date:

== Versions

include::{partialsdir}/dyn/versions.adoc[]

== Repositories

Special repositories:

* Latest release:
** http://repository.rudder.io/apt/latest/
** http://repository.rudder.io/rpm/latest/
* Latest nightly builds:
** http://repository.rudder.io/apt/nightly/
** http://repository.rudder.io/rpm/nightly/

