site:
  title: Rudder Documentation
  start_page: get-started::index
content:
  sources:
  - url: ../
    branches: master
    start_path: unified/rudder-by-example
  - url: ../
    branches: master
    start_path: unified/get-started
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
